import defaultMdxComponents from 'fumadocs-ui/mdx'
import type { MDXComponents } from 'mdx/types'
import { Preview } from '@/components/preview'
import {
  Alert,
  AlertTitle,
  AlertDescription,
  Avatar,
  AvatarImage,
  AvatarFallback,
  Badge,
  Button,
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
  Checkbox,
  Input,
  Kbd,
  Label,
  Progress,
  Separator,
  Skeleton,
  Switch,
  Toggle,
  InfoIcon,
  BoldIcon,
} from '@/components/mdx-previews'

export function getMDXComponents(components?: MDXComponents): MDXComponents {
  return {
    ...defaultMdxComponents,
    Preview,
    Alert,
    AlertTitle,
    AlertDescription,
    Avatar,
    AvatarImage,
    AvatarFallback,
    Badge,
    Button,
    Card,
    CardHeader,
    CardTitle,
    CardDescription,
    CardContent,
    CardFooter,
    Checkbox,
    Input,
    Kbd,
    Label,
    Progress,
    Separator,
    Skeleton,
    Switch,
    Toggle,
    InfoIcon,
    BoldIcon,
    ...components,
  }
}
